name: erik_haydar
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  bottom_bar: ^2.0.2
  carousel_slider: ^4.1.1
  cupertino_icons: ^1.0.2
  device_info_plus: ^7.0.1
  dio: ^4.0.4
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.1.5
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  http: ^0.13.5
  image_picker: ^0.8.5+3
  url_launcher: ^6.1.6
  lottie: ^1.4.0
  mask_text_input_formatter: ^2.4.0
  otp_text_field: ^1.1.3
  provider: ^6.0.4
  shared_preferences: ^2.0.15
  persistent_bottom_nav_bar_v2: ^4.2.6
  cached_network_image: ^3.2.2
  dropdown_button2: ^1.8.9
  just_audio: ^0.9.30
  rxdart: '>=0.26.0 <0.28.0'
  audio_session: ^0.1.10




dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/image/
    - assets/language/
    - assets/json/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter-Black.ttf
          weight: 900
