// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0O07dI4n0xM2XP5UB8ILhMUvVjmYhWPc',
    appId: '1:628452998985:web:7236ffc5b7cee069892498',
    messagingSenderId: '628452998985',
    projectId: 'erikhaydar-cc050',
    authDomain: 'erikhaydar-cc050.firebaseapp.com',
    storageBucket: 'erikhaydar-cc050.appspot.com',
    measurementId: 'G-RKDXKPTPSX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4tJW7tsP1y46tx0g-bqemLk1oL3BnC4c',
    appId: '1:628452998985:android:60b76a0abd28d0d0892498',
    messagingSenderId: '628452998985',
    projectId: 'erikhaydar-cc050',
    storageBucket: 'erikhaydar-cc050.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUZzwLXLso7dU04cMa5L5TN6kK0jNFlZo',
    appId: '1:628452998985:ios:bc10d058ffdfe7fa892498',
    messagingSenderId: '628452998985',
    projectId: 'erikhaydar-cc050',
    storageBucket: 'erikhaydar-cc050.appspot.com',
    iosClientId: '628452998985-a6d08d82kqe2kqa934n6el39ofivkn32.apps.googleusercontent.com',
    iosBundleId: 'com.example.erikHaydar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUZzwLXLso7dU04cMa5L5TN6kK0jNFlZo',
    appId: '1:628452998985:ios:bc10d058ffdfe7fa892498',
    messagingSenderId: '628452998985',
    projectId: 'erikhaydar-cc050',
    storageBucket: 'erikhaydar-cc050.appspot.com',
    iosClientId: '628452998985-a6d08d82kqe2kqa934n6el39ofivkn32.apps.googleusercontent.com',
    iosBundleId: 'com.example.erikHaydar',
  );
}
